Remove env command dependency

diff --git a/src/shdotenv b/src/shdotenv
--- a/src/shdotenv
+++ b/src/shdotenv
@@ -45,7 +45,7 @@ usage() {
     "  environment variable name that are valid as identifier for posix shell."
 }
 
-abort() { echo "$_shdotenv_progname:" "$@" >&2 && exit 1; }
+abort() { echo "$_shdotenv_progname:" "$1" >&2 && exit "${2:-1}"; }
 requires() {
   [ $# -gt 1 ] || abort "error: $1 option requires an argument"
   _shdotenv_pos=$((_shdotenv_pos + 1))
@@ -98,7 +98,7 @@ unexport() {
 }
 
 init_vars() {
-  set -- _shdotenv_progname="$1" _shdotenv_parser= _shdotenv_exporter=
+  set -- _shdotenv_progname= _shdotenv_parser= _shdotenv_exporter=
   set -- "$@" _shdotenv_dialect= _shdotenv_format="${SHDOTENV_FORMAT:-}"
   set -- "$@" _shdotenv_envfiles= _shdotenv_overload=
   set -- "$@" _shdotenv_allexport=1 _shdotenv_nounset=1
@@ -148,13 +148,33 @@ exec_exporter() {
   "${SHDOTENV_AWK:-awk}" "$@"
 }
 
-init_vars "${0##*/}"
+exists() {
+  case $1 in
+    */*) [ -x "$1" ] && return 0 ;;
+    *)
+      set -- "$1" "${PATH:-}:"
+      while [ "$2" ]; do
+        set -- "$1" "${2#*:}" "${2%%:*}"
+        if [ -f "${3:-./}/$1" ] && [ -x "${3:-./}/$1" ]; then
+          return 0
+        fi
+      done
+      ;;
+  esac
+  return 1
+}
+
+init_vars
+_shdotenv_progname="${0##*/}"
 parse_options "$@"
 
 read_config_file ".shdotenv"
 
 escape_awk_value _shdotenv_format "$_shdotenv_format"
 escape_awk_value _shdotenv_grep "$_shdotenv_grep"
+if ! exists "${SHDOTENV_AWK:-awk}"; then
+  abort "the awk command is required"
+fi
 
 if [ $(($# - _shdotenv_pos + 1)) -eq 0 ]; then
   [ "$_shdotenv_quiet" ] && exec >/dev/null
@@ -169,6 +189,9 @@ else
       shift
       exec_exporter "$@"
       ;;
-    *) exec env "$@" ;;
+    *)
+      exists "$1" || abort "$1: command not found" 127
+      exec "$@"
+      ;;
   esac
 fi
